In [4]:
%config IPCompleter.greedy=True
import torch as th

In [9]:
x = th.tensor([5.5,3])
x

tensor([5.5000, 3.0000])

In [34]:
x = x.new_ones(5,3)
z = th.rand_like(x)
print(x)
print(y)
print(z)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.1583, 0.6091, 0.1460],
        [0.6774, 0.0909, 0.0605],
        [0.5275, 0.6534, 0.1577],
        [0.6255, 0.3651, 0.3913],
        [0.8498, 0.4404, 0.9638]])


In [35]:
# Addition
print(x+z)
print(th.add(x,z))
result = th.rand_like(x)
th.add(x,z,out = result)
print(result)


tensor([[1.1583, 1.6091, 1.1460],
        [1.6774, 1.0909, 1.0605],
        [1.5275, 1.6534, 1.1577],
        [1.6255, 1.3651, 1.3913],
        [1.8498, 1.4404, 1.9638]])
tensor([[1.1583, 1.6091, 1.1460],
        [1.6774, 1.0909, 1.0605],
        [1.5275, 1.6534, 1.1577],
        [1.6255, 1.3651, 1.3913],
        [1.8498, 1.4404, 1.9638]])
tensor([[1.1583, 1.6091, 1.1460],
        [1.6774, 1.0909, 1.0605],
        [1.5275, 1.6534, 1.1577],
        [1.6255, 1.3651, 1.3913],
        [1.8498, 1.4404, 1.9638]])


In [53]:
# Access
print( result[0,:])
# Get as Python number Only for single element tensors
print( result[0,1].item())

tensor([1.1583, 1.6091, 1.1460])
1.6091046333312988


In [54]:
# Reshape/Resize
x = th.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x.size(), y.size(), z.size())


torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [72]:
# Torch to Numpy and inverse
a = th.ones(4,5)
print(type(a))
b = a.numpy()
print(type(b))

# Add is NOT an inplace operation and returns a Tensor
c = a.add(1)
print(a)
print(c)

# Add_ is an inplace operation and changes the actual Tensor and hence the numpy variable
a.add_(2)
print(a)
print(b)


<class 'torch.Tensor'>
<class 'numpy.ndarray'>
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]])
tensor([[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]])
[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]


In [75]:
import numpy as np
d = th.from_numpy(b)
np.add(b,2, out = b)
print(b)
print(d)

[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]
tensor([[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]])


In [82]:
# Tensors in CUDA
if th.cuda.is_available():
    device = th.device("cuda")
    y = th.ones_like(z,device = device)
    z = z.to(device)
    sum = y + z
    print(sum)
    print(sum.to("cpu"),th.double)

tensor([[ 0.4919,  0.5584,  0.9684,  1.6930,  0.2111,  0.9997,  0.7734, -0.2431],
        [ 0.2887,  0.2394,  0.5132,  2.1081,  0.8562,  0.9943,  1.3071,  3.3660]],
       device='cuda:0')
tensor([[ 0.4919,  0.5584,  0.9684,  1.6930,  0.2111,  0.9997,  0.7734, -0.2431],
        [ 0.2887,  0.2394,  0.5132,  2.1081,  0.8562,  0.9943,  1.3071,  3.3660]]) torch.float64
